### ISSUE TITLE
PA Review: User auth

### ISSUE THREAD

**Issue by MatthewWanderers** [MatthewWanderers/EventNight#2] opened 2018-04-09 17:31 UTC
- [x] Backend done
- [x] Frontend done

- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site(most features are available to public, but must be logged in to register or create and event)
- [x] Users can't use certain features without logging in (creating/registering for an event)

**Comment by AAlfarho** [comment] 2018-04-10 16:27
Good job on the user auth, just one detail.

- [x] Whats the difference between the `login` & `Demo Account` button, it seems that they both try to login whatever is there in the username/password fields, if I remove the `Demo Account` and password from the fields, and use the `Demo account` button, it no longer logs the demo account.

Let's fix this before closing this MVP.

Assign this issue back to me once the issue is addressed and pushed live to Heroku.

**Comment by MatthewWanderers** [comment] 2018-04-10 18:07
Fixed. Forgot I had to update that!

**Comment by AAlfarho** [comment] 2018-04-11 16:19
Great, latest version live on Heroku addresses the feedback present here, this MVP is now closed, kudos!

**Closed as completed by AAlfarho** 2018-04-11 16:19 UTC
